// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Heading field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Paragraph field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogTestDocumentDataSlicesSlice =
  | LandlordsSlice
  | LandLordCtaSlice
  | TestimonialsSlice
  | RealEstateSectionSlice
  | PropertySlice
  | HeroSlice;

/**
 * Content for blogs documents
 */
interface BlogTestDocumentData {
  /**
   * BlogImage field in *blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.blogimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blogimage: prismic.ImageField<never>;

  /**
   * BlogHeading field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.blogheading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blogheading: prismic.KeyTextField;

  /**
   * BlogParagraph field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.blogparagraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blogparagraph: prismic.KeyTextField;

  /**
   * Slice Zone field in *blogs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogTestDocumentDataSlicesSlice> /**
   * Meta Title field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_test.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_test.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Image field in *blogs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.image
   * - **Tab**: TabSection
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  image: prismic.ImageField<never>;

  /**
   * Prize field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.prize
   * - **Tab**: TabSection
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  prize: prismic.KeyTextField;

  /**
   * Heading field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.heading
   * - **Tab**: TabSection
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Paragraph field in *blogs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_test.paragraph
   * - **Tab**: TabSection
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * blogs document from Prismic
 *
 * - **API ID**: `blog_test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogTestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogTestDocumentData>,
    "blog_test",
    Lang
  >;

/**
 * Item in *Footer → FooterTitle*
 */
export interface FooterDocumentDataFootertitleItem {
  /**
   * FooterTitles field in *Footer → FooterTitle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footertitle[].footertitles
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footertitles: prismic.KeyTextField;
}

/**
 * Item in *Footer → FooterLinks*
 */
export interface FooterDocumentDataFooterlinksItem {
  /**
   * FooterLabel field in *Footer → FooterLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerlinks[].footerlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footerlabel: prismic.KeyTextField;

  /**
   * FooterLink field in *Footer → FooterLinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerlinks[].footerlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footerlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → FooterIcons*
 */
export interface FooterDocumentDataFootericonsItem {
  /**
   * Icons field in *Footer → FooterIcons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footericons[].icons
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icons: prismic.SelectField<"FaceBook" | "Linkedin" | "Twitter" | "Instagram">;

  /**
   * IconsLink field in *Footer → FooterIcons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footericons[].iconslink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iconslink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * FooterLogo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerlogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footerlogo: prismic.ImageField<never>;

  /**
   * FooterTitle field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footertitle[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footertitle: prismic.GroupField<Simplify<FooterDocumentDataFootertitleItem>>;

  /**
   * FooterLinks field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerlinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footerlinks: prismic.GroupField<Simplify<FooterDocumentDataFooterlinksItem>>;

  /**
   * CopyRight field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * FooterIcons field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footericons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footericons: prismic.GroupField<Simplify<FooterDocumentDataFootericonsItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * Label field in *Header → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Header → AuthButtons*
 */
export interface HeaderDocumentDataAuthbuttonsItem {
  /**
   * Label field in *Header → AuthButtons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.authbuttons[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Header → AuthButtons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.authbuttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Variation field in *Header → AuthButtons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: header.authbuttons[].variation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variation: prismic.SelectField<"Colored" | "Transparent">;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;

  /**
   * AuthButtons field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.authbuttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  authbuttons: prismic.GroupField<Simplify<HeaderDocumentDataAuthbuttonsItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | TestimonialsSlice
  | LandLordCtaSlice
  | PropertySlice
  | RealEstateSectionSlice
  | LandlordsSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | TestimonialsSlice
  | RealEstateSectionSlice
  | PropertySlice
  | LandlordsSlice
  | LandLordCtaSlice
  | HeroSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Heading field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | BlogDocument
  | BlogTestDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | PageDocument;

/**
 * Item in *Hero → Default → Primary → Card*
 */
export interface HeroSliceDefaultPrimaryCardItem {
  /**
   * CardImage field in *Hero → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.card[].card_Image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_Image: prismic.ImageField<never>;

  /**
   * CardPrize field in *Hero → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.card[].card_Prize
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_Prize: prismic.KeyTextField;

  /**
   * CardText field in *Hero → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.card[].cardtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardtext: prismic.KeyTextField;

  /**
   * CardPara field in *Hero → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.card[].cardpara
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardpara: prismic.KeyTextField;
}

/**
 * Item in *Hero → Default → Primary → CardSvg*
 */
export interface HeroSliceDefaultPrimaryCardsvgItem {
  /**
   * CardSvgImage field in *Hero → Default → Primary → CardSvg*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cardsvg[].cardsvgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardsvgimage: prismic.ImageField<never>;

  /**
   * CardSvgText field in *Hero → Default → Primary → CardSvg*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cardsvg[].cardsvgtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardsvgtext: prismic.KeyTextField;
}

/**
 * Item in *Hero → Default → Primary → SmallCardSvg*
 */
export interface HeroSliceDefaultPrimarySmallcardsvgItem {
  /**
   * SmallCardSvgImage field in *Hero → Default → Primary → SmallCardSvg*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.smallcardsvg[].smallcardsvgimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  smallcardsvgimage: prismic.ImageField<never>;

  /**
   * SmallCardSvgText field in *Hero → Default → Primary → SmallCardSvg*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.smallcardsvg[].smallcardsvgtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smallcardsvgtext: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * BannerImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.banner_Image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_Image: prismic.ImageField<never>;

  /**
   * Card field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCardItem>>;

  /**
   * CardSvg field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cardsvg[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardsvg: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCardsvgItem>>;

  /**
   * SmallCardSvg field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.smallcardsvg[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  smallcardsvg: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimarySmallcardsvgItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *LandLordCta → Default → Primary*
 */
export interface LandLordCtaSliceDefaultPrimary {
  /**
   * Text field in *LandLordCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: land_lord_cta.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Heading field in *LandLordCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: land_lord_cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Paragraph field in *LandLordCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: land_lord_cta.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Placeholder field in *LandLordCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: land_lord_cta.default.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Btnlabel field in *LandLordCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: land_lord_cta.default.primary.btnlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btnlabel: prismic.KeyTextField;

  /**
   * SmallText field in *LandLordCta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: land_lord_cta.default.primary.smalltext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  smalltext: prismic.KeyTextField;
}

/**
 * Default variation for LandLordCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandLordCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandLordCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LandLordCta*
 */
type LandLordCtaSliceVariation = LandLordCtaSliceDefault;

/**
 * LandLordCta Shared Slice
 *
 * - **API ID**: `land_lord_cta`
 * - **Description**: LandLordCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandLordCtaSlice = prismic.SharedSlice<
  "land_lord_cta",
  LandLordCtaSliceVariation
>;

/**
 * Item in *Landlords → Default → Primary → ToggleButton*
 */
export interface LandlordsSliceDefaultPrimaryTogglebuttonItem {
  /**
   * Label field in *Landlords → Default → Primary → ToggleButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.togglebutton[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Landlords → Default → Primary*
 */
export interface LandlordsSliceDefaultPrimary {
  /**
   * LandlordImage field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.landlordimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  landlordimage: prismic.ImageField<never>;

  /**
   * LandlordHeading field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.landlordheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  landlordheading: prismic.KeyTextField;

  /**
   * LandlordPara field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.landlordpara
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  landlordpara: prismic.KeyTextField;

  /**
   * SmallImage field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.smallimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  smallimage: prismic.ImageField<never>;

  /**
   * ToggleButton field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.togglebutton[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  togglebutton: prismic.GroupField<
    Simplify<LandlordsSliceDefaultPrimaryTogglebuttonItem>
  >;

  /**
   * BtnHeading field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.btnheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btnheading: prismic.KeyTextField;

  /**
   * BtnPara field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.btnpara
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btnpara: prismic.KeyTextField;

  /**
   * Btnlabel field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.btnlabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btnlabel: prismic.KeyTextField;

  /**
   * BtnLink field in *Landlords → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landlords.default.primary.btnlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btnlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Landlords Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandlordsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandlordsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Landlords*
 */
type LandlordsSliceVariation = LandlordsSliceDefault;

/**
 * Landlords Shared Slice
 *
 * - **API ID**: `landlords`
 * - **Description**: Landlords
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandlordsSlice = prismic.SharedSlice<
  "landlords",
  LandlordsSliceVariation
>;

/**
 * Item in *Property → Default → Primary → Cards*
 */
export interface PropertySliceDefaultPrimaryCardsItem {
  /**
   * CardImage field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardimage: prismic.ImageField<never>;

  /**
   * CardPrize field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardprize
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardprize: prismic.KeyTextField;

  /**
   * CardMonth field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardmonth
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardmonth: prismic.KeyTextField;

  /**
   * CardHeading field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardheading: prismic.KeyTextField;

  /**
   * CardPara field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardpara
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardpara: prismic.KeyTextField;

  /**
   * CardHeartImg field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardheartimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardheartimg: prismic.ImageField<never>;

  /**
   * CardLink field in *Property → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[].cardlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Property → Default → Primary → CardSvgText*
 */
export interface PropertySliceDefaultPrimaryCardsvgtextItem {
  /**
   * CardSmallImage field in *Property → Default → Primary → CardSvgText*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cardsvgtext[].cardsmallimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardsmallimage: prismic.ImageField<never>;

  /**
   * CardSmallText field in *Property → Default → Primary → CardSvgText*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cardsvgtext[].cardsmalltext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardsmalltext: prismic.KeyTextField;

  /**
   * CardSmallText2 field in *Property → Default → Primary → CardSvgText*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cardsvgtext[].cardsmalltext2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardsmalltext2: prismic.KeyTextField;
}

/**
 * Primary content in *Property → Default → Primary*
 */
export interface PropertySliceDefaultPrimary {
  /**
   * PropertyHeading field in *Property → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.propertyheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  propertyheading: prismic.KeyTextField;

  /**
   * PropertyText field in *Property → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.propertytext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  propertytext: prismic.KeyTextField;

  /**
   * Cards field in *Property → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<PropertySliceDefaultPrimaryCardsItem>>;

  /**
   * CardSvgText field in *Property → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: property.default.primary.cardsvgtext[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardsvgtext: prismic.GroupField<
    Simplify<PropertySliceDefaultPrimaryCardsvgtextItem>
  >;
}

/**
 * Default variation for Property Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PropertySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Property*
 */
type PropertySliceVariation = PropertySliceDefault;

/**
 * Property Shared Slice
 *
 * - **API ID**: `property`
 * - **Description**: Property
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertySlice = prismic.SharedSlice<
  "property",
  PropertySliceVariation
>;

/**
 * Item in *RealEstateSection → Default → Primary → RealProperties*
 */
export interface RealEstateSectionSliceDefaultPrimaryRealpropertiesItem {
  /**
   * RealPropertiesImage field in *RealEstateSection → Default → Primary → RealProperties*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realproperties[].realprop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  realprop: prismic.ImageField<never>;

  /**
   * RealPropertiesHeading field in *RealEstateSection → Default → Primary → RealProperties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realproperties[].realpropertiesheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  realpropertiesheading: prismic.KeyTextField;

  /**
   * RealPropertiesText field in *RealEstateSection → Default → Primary → RealProperties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realproperties[].realpropertiestext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  realpropertiestext: prismic.KeyTextField;
}

/**
 * Primary content in *RealEstateSection → Default → Primary*
 */
export interface RealEstateSectionSliceDefaultPrimary {
  /**
   * RealHeading field in *RealEstateSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  realheading: prismic.KeyTextField;

  /**
   * RealPara field in *RealEstateSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realpara
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  realpara: prismic.KeyTextField;

  /**
   * RealImage field in *RealEstateSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  realimage: prismic.ImageField<never>;

  /**
   * RealProperties field in *RealEstateSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: real_estate_section.default.primary.realproperties[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  realproperties: prismic.GroupField<
    Simplify<RealEstateSectionSliceDefaultPrimaryRealpropertiesItem>
  >;
}

/**
 * Default variation for RealEstateSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RealEstateSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RealEstateSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RealEstateSection*
 */
type RealEstateSectionSliceVariation = RealEstateSectionSliceDefault;

/**
 * RealEstateSection Shared Slice
 *
 * - **API ID**: `real_estate_section`
 * - **Description**: RealEstateSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RealEstateSectionSlice = prismic.SharedSlice<
  "real_estate_section",
  RealEstateSectionSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → TestimonialsData*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsdataItem {
  /**
   * quote field in *Testimonials → Default → Primary → TestimonialsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialsdata[].quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField;

  /**
   * name field in *Testimonials → Default → Primary → TestimonialsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialsdata[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * role field in *Testimonials → Default → Primary → TestimonialsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialsdata[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * TestimonialHeading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonialheading: prismic.KeyTextField;

  /**
   * TestimonialText field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonialtext: prismic.KeyTextField;

  /**
   * TestimonialsData field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialsdata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonialsdata: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsdataItem>
  >;

  /**
   * TestimonialImage field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonialimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonialimage: prismic.ImageField<never>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogTestDocument,
      BlogTestDocumentData,
      BlogTestDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFootertitleItem,
      FooterDocumentDataFooterlinksItem,
      FooterDocumentDataFootericonsItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HeaderDocumentDataAuthbuttonsItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimaryCardItem,
      HeroSliceDefaultPrimaryCardsvgItem,
      HeroSliceDefaultPrimarySmallcardsvgItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LandLordCtaSlice,
      LandLordCtaSliceDefaultPrimary,
      LandLordCtaSliceVariation,
      LandLordCtaSliceDefault,
      LandlordsSlice,
      LandlordsSliceDefaultPrimaryTogglebuttonItem,
      LandlordsSliceDefaultPrimary,
      LandlordsSliceVariation,
      LandlordsSliceDefault,
      PropertySlice,
      PropertySliceDefaultPrimaryCardsItem,
      PropertySliceDefaultPrimaryCardsvgtextItem,
      PropertySliceDefaultPrimary,
      PropertySliceVariation,
      PropertySliceDefault,
      RealEstateSectionSlice,
      RealEstateSectionSliceDefaultPrimaryRealpropertiesItem,
      RealEstateSectionSliceDefaultPrimary,
      RealEstateSectionSliceVariation,
      RealEstateSectionSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsdataItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
