// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  land_lord_cta: dynamic(() => import("./LandLordCta")),
  landlords: dynamic(() => import("./Landlords")),
  property: dynamic(() => import("./Property")),
  real_estate_section: dynamic(() => import("./RealEstateSection")),
  testimonials: dynamic(() => import("./Testimonials")),
};
